/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package status;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static status.Funcoes.consultaEnergia;

/**
 *
 * @author a1700596
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        Agendador rodando = new Agendador(jLabelOutput, jLabelAdobeReader, jLabelAvast, jLabeldotNet, jLabelDropbox, jLabelGoogleChrome, jLabelKlite, jLabelOffice, jLabelWinrar,jButtonEnergia,jButtonTrocarUsuario,jButtonFirewall,jButtonPostgres,jLabelAtiveAdmin,jLabelAthosPostgres,jLabelAthosInstalado,jLabelStatosPostgres,jLabelStatosDNS,jLabelStatosDHCP,jLabelStatosFirewall,jLabelStatosSpooler,jLabelStatosWindowsUpdate,jButtonWinUpdate,jButtonRelogio);
        Inicializador inicia = new Inicializador(jCheckBoxAthosBackup,jCheckBoxCapicom,jCheckBoxDesempenho,jCheckBoxInternet,jCheckBoxRede,jCheckBoxSite,jCheckBoxWallpaper,jCheckBoxWindowsUpdate, jLabelVersaoWindows,jLabelModelo,jLabelProcessador,jLabelMemoria,jLabelTipoIP,jLabelIP);
        rodando.start();
        inicia.start();
        setIconImage(new ImageIcon(getClass().getResource("/imagens/analytics-monitor-green.png")).getImage());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEnviadostxt = new javax.swing.JLabel();
        jLabelRecebidostxt = new javax.swing.JLabel();
        jLabelMédia = new javax.swing.JLabel();
        jLabelEnviados = new javax.swing.JLabel();
        jLabelRecebidos = new javax.swing.JLabel();
        jLabelMedia = new javax.swing.JLabel();
        jProgressBarPing = new javax.swing.JProgressBar();
        jButtonPing = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerTamanhoDownload = new javax.swing.JSpinner();
        jLabelTempoDownload = new javax.swing.JLabel();
        jLabelMediaDownload = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTrocarUsuario = new javax.swing.JLabel();
        jLabelEnergia = new javax.swing.JLabel();
        jButtonEnergia = new javax.swing.JButton();
        jButtonTrocarUsuario = new javax.swing.JButton();
        jLabelFirewall = new javax.swing.JLabel();
        jButtonFirewall = new javax.swing.JButton();
        jLabelAtiveAdmin = new javax.swing.JLabel();
        jLabelRestartPostgres = new javax.swing.JLabel();
        jButtonPostgres = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabelLightGreenOff = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonWinUpdate = new javax.swing.JButton();
        jButtonRelogio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelVersaoWindowsText = new javax.swing.JLabel();
        jLabelOutput = new javax.swing.JLabel();
        jLabelVersaoWindows = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelAdobeReadertxt = new javax.swing.JLabel();
        jLabelAdobeReader = new javax.swing.JLabel();
        jLabeldotNettxt = new javax.swing.JLabel();
        jLabeldotNet = new javax.swing.JLabel();
        jLabelDropboxtxt = new javax.swing.JLabel();
        jLabelDropbox = new javax.swing.JLabel();
        jLabelOfficetxt = new javax.swing.JLabel();
        jLabelOffice = new javax.swing.JLabel();
        jLabelWinrartxt = new javax.swing.JLabel();
        jLabelAvasttxt = new javax.swing.JLabel();
        jLabelWinrar = new javax.swing.JLabel();
        jLabelAvast = new javax.swing.JLabel();
        jLabelGoogleChrometxt = new javax.swing.JLabel();
        jLabelGoogleChrome = new javax.swing.JLabel();
        jLabelKlitetxt1 = new javax.swing.JLabel();
        jLabelKlite = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAthosPostgres = new javax.swing.JLabel();
        jLabelAthosInstalado = new javax.swing.JLabel();
        jCheckBoxAthosBackup = new javax.swing.JCheckBox();
        jCheckBoxDesempenho = new javax.swing.JCheckBox();
        jCheckBoxRede = new javax.swing.JCheckBox();
        jCheckBoxSite = new javax.swing.JCheckBox();
        jCheckBoxWallpaper = new javax.swing.JCheckBox();
        jCheckBoxWindowsUpdate = new javax.swing.JCheckBox();
        jCheckBoxInternet = new javax.swing.JCheckBox();
        jCheckBoxCapicom = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelStatosDNS = new javax.swing.JLabel();
        jLabelStatosDHCP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelStatosFirewall = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelStatosSpooler = new javax.swing.JLabel();
        jLabelStatosWindowsUpdate = new javax.swing.JLabel();
        jLabelStatosPostgres = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelPlacaMae = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelProcessador = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelIP = new javax.swing.JLabel();
        jLabelPlacaMae1 = new javax.swing.JLabel();
        jLabelMemoria = new javax.swing.JLabel();
        jLabelTipoIP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sthatos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rede", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelEnviadostxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnviadostxt.setText("Enviados");
        jLabelEnviadostxt.setMaximumSize(new java.awt.Dimension(143, 14));
        jLabelEnviadostxt.setMinimumSize(new java.awt.Dimension(143, 14));
        jLabelEnviadostxt.setPreferredSize(new java.awt.Dimension(143, 14));

        jLabelRecebidostxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRecebidostxt.setText("Recebidos");

        jLabelMédia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMédia.setText("Latência");

        jLabelEnviados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnviados.setText("0");
        jLabelEnviados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelRecebidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRecebidos.setText("0");
        jLabelRecebidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelMedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMedia.setText("0");
        jLabelMedia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonPing.setText("Ping");
        jButtonPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPingActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Size(mb)");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tempo");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Média");

        jSpinnerTamanhoDownload.setModel(new javax.swing.SpinnerListModel(new String[] {"10", "30", "50", "100", "200"}));

        jLabelTempoDownload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempoDownload.setText("0s");

        jLabelMediaDownload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMediaDownload.setText("0mb/s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarPing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEnviadostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelRecebidostxt, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(jLabelRecebidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMédia, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabelMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonPing)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerTamanhoDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTempoDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabelMediaDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnviadostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRecebidostxt)
                    .addComponent(jLabelMédia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnviados)
                    .addComponent(jLabelRecebidos)
                    .addComponent(jLabelMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTamanhoDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTempoDownload)
                    .addComponent(jLabelMediaDownload))
                .addGap(18, 18, 18)
                .addComponent(jProgressBarPing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonPing)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Query's", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelTrocarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTrocarUsuario.setText("Trocar Usuário");

        jLabelEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnergia.setText("Energia");

        jButtonEnergia.setText("Ok");
        jButtonEnergia.setEnabled(false);
        jButtonEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnergiaActionPerformed(evt);
            }
        });

        jButtonTrocarUsuario.setText("Ok");
        jButtonTrocarUsuario.setEnabled(false);
        jButtonTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocarUsuarioActionPerformed(evt);
            }
        });

        jLabelFirewall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFirewall.setText("Ativar Firewall");

        jButtonFirewall.setText("Ok");
        jButtonFirewall.setEnabled(false);
        jButtonFirewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirewallActionPerformed(evt);
            }
        });

        jLabelAtiveAdmin.setForeground(java.awt.Color.red);
        jLabelAtiveAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtiveAdmin.setText("Ative o Administrador");

        jLabelRestartPostgres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRestartPostgres.setText("Postgres");

        jButtonPostgres.setText("Ok");
        jButtonPostgres.setEnabled(false);
        jButtonPostgres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostgresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Windows Update");

        jLabel15.setText("Relógio Windows");

        jButtonWinUpdate.setText("Ok");
        jButtonWinUpdate.setEnabled(false);
        jButtonWinUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWinUpdateActionPerformed(evt);
            }
        });

        jButtonRelogio.setText("Ok");
        jButtonRelogio.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButtonTrocarUsuario))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButtonFirewall, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonEnergia)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonPostgres)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAtiveAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelLightGreenOff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelTrocarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(jLabelFirewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelRestartPostgres, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButtonWinUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonRelogio)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrocarUsuario)
                    .addComponent(jLabelEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTrocarUsuario)
                    .addComponent(jButtonEnergia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirewall)
                    .addComponent(jLabelRestartPostgres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFirewall)
                    .addComponent(jButtonPostgres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWinUpdate)
                    .addComponent(jButtonRelogio))
                .addGap(39, 39, 39)
                .addComponent(jLabelAtiveAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLightGreenOff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações do Windows", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(252, 110));

        jLabelAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdministrador.setText("Administrador");
        jLabelAdministrador.setMaximumSize(new java.awt.Dimension(72, 14));
        jLabelAdministrador.setMinimumSize(new java.awt.Dimension(72, 14));
        jLabelAdministrador.setPreferredSize(new java.awt.Dimension(72, 14));

        jLabelVersaoWindowsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersaoWindowsText.setText("Versão Windows");
        jLabelVersaoWindowsText.setMaximumSize(new java.awt.Dimension(72, 14));
        jLabelVersaoWindowsText.setMinimumSize(new java.awt.Dimension(72, 14));
        jLabelVersaoWindowsText.setPreferredSize(new java.awt.Dimension(72, 14));

        jLabelOutput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOutput.setForeground(new java.awt.Color(255, 51, 51));
        jLabelOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOutput.setText("Não");

        jLabelVersaoWindows.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVersaoWindows.setForeground(new java.awt.Color(255, 0, 51));
        jLabelVersaoWindows.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersaoWindows.setText("Versão");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelVersaoWindowsText, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabelVersaoWindows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelVersaoWindowsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutput)
                    .addComponent(jLabelVersaoWindows))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelAdobeReadertxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdobeReadertxt.setText("Adobe Reader");

        jLabelAdobeReader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdobeReader.setForeground(java.awt.Color.red);
        jLabelAdobeReader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdobeReader.setText("Não");

        jLabeldotNettxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldotNettxt.setText("dotNet");

        jLabeldotNet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeldotNet.setForeground(java.awt.Color.red);
        jLabeldotNet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldotNet.setText("Não");

        jLabelDropboxtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDropboxtxt.setText("Dropbox");

        jLabelDropbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDropbox.setForeground(java.awt.Color.red);
        jLabelDropbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDropbox.setText("Não");

        jLabelOfficetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOfficetxt.setText("Microsoft Office");

        jLabelOffice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOffice.setForeground(java.awt.Color.red);
        jLabelOffice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOffice.setText("Não");

        jLabelWinrartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinrartxt.setText("Winrar");

        jLabelAvasttxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvasttxt.setText("Avast Antivirus");

        jLabelWinrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelWinrar.setForeground(java.awt.Color.red);
        jLabelWinrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinrar.setText("Não");

        jLabelAvast.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAvast.setForeground(java.awt.Color.red);
        jLabelAvast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvast.setText("Não");

        jLabelGoogleChrometxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGoogleChrometxt.setText("Google Chrome");

        jLabelGoogleChrome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGoogleChrome.setForeground(java.awt.Color.red);
        jLabelGoogleChrome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGoogleChrome.setText("Não");

        jLabelKlitetxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKlitetxt1.setText("K-Lite Codec Pack");

        jLabelKlite.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelKlite.setForeground(java.awt.Color.red);
        jLabelKlite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKlite.setText("Não");

        jSeparator1.setForeground(java.awt.Color.black);
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Athos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Postgres");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instalado");

        jLabelAthosPostgres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAthosPostgres.setForeground(java.awt.Color.red);
        jLabelAthosPostgres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAthosPostgres.setText("Não");

        jLabelAthosInstalado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAthosInstalado.setForeground(java.awt.Color.red);
        jLabelAthosInstalado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAthosInstalado.setText("Não");

        jCheckBoxAthosBackup.setText("AthosBackup");
        jCheckBoxAthosBackup.setEnabled(false);
        jCheckBoxAthosBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAthosBackupActionPerformed(evt);
            }
        });

        jCheckBoxDesempenho.setText("Desempenho ");
        jCheckBoxDesempenho.setEnabled(false);
        jCheckBoxDesempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDesempenhoActionPerformed(evt);
            }
        });

        jCheckBoxRede.setText("Perfil de Rede");
        jCheckBoxRede.setEnabled(false);
        jCheckBoxRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRedeActionPerformed(evt);
            }
        });

        jCheckBoxSite.setText("Site");
        jCheckBoxSite.setEnabled(false);
        jCheckBoxSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSiteActionPerformed(evt);
            }
        });

        jCheckBoxWallpaper.setText("Wallpaper");
        jCheckBoxWallpaper.setEnabled(false);
        jCheckBoxWallpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWallpaperActionPerformed(evt);
            }
        });

        jCheckBoxWindowsUpdate.setText("Windows Update");
        jCheckBoxWindowsUpdate.setEnabled(false);
        jCheckBoxWindowsUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWindowsUpdateActionPerformed(evt);
            }
        });

        jCheckBoxInternet.setText("Opções/Internet");
        jCheckBoxInternet.setEnabled(false);
        jCheckBoxInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInternetActionPerformed(evt);
            }
        });

        jCheckBoxCapicom.setText("Capicom");
        jCheckBoxCapicom.setEnabled(false);
        jCheckBoxCapicom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCapicomActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(java.awt.Color.black);
        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check-List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGoogleChrometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGoogleChrome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKlitetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKlite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOfficetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWinrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelWinrartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxWindowsUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxCapicom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxAthosBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxRede, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAdobeReadertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAdobeReader, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAvasttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAvast, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabeldotNettxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabeldotNet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDropboxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelAthosPostgres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAthosInstalado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelAdobeReadertxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAdobeReader))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelAvasttxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAvast)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabeldotNettxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeldotNet))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelDropboxtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDropbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelGoogleChrometxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGoogleChrome))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelKlitetxt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKlite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelWinrartxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelWinrar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelOfficetxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOffice)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAthosPostgres)
                    .addComponent(jLabelAthosInstalado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAthosBackup)
                    .addComponent(jCheckBoxDesempenho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRede)
                    .addComponent(jCheckBoxSite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWindowsUpdate)
                    .addComponent(jCheckBoxWallpaper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxInternet)
                    .addComponent(jCheckBoxCapicom))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status Serviços", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel5.setToolTipText("<html>\nMostra o Status dos Serviços Essenciais para Uso do Athos\n<br>\nAo clicar em um serviço Parado ele inicia o serviço e seta a inicialização como Automática\n<br>\nAo clicar em um serviço Iniciado ele para o serviço e seta a inicialização como  DESABILITADO\n</html>");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente DNS");
        jLabel3.setToolTipText("Sistema de Nomes de Domínio, transforma nomes em ip's.\\n \nCaso não esteja funcionando corretamente até mesmo a\\n nomenclatura dos computadores não funcionara corretamente.\\n\nEx: Conexão não funciona pelo nome, mais funciona pelo ip.\\n");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cliente DHCP");

        jLabelStatosDNS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosDNS.setForeground(java.awt.Color.red);
        jLabelStatosDNS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosDNS.setText("Parado");
        jLabelStatosDNS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosDNSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosDNSMouseEntered(evt);
            }
        });

        jLabelStatosDHCP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosDHCP.setForeground(java.awt.Color.red);
        jLabelStatosDHCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosDHCP.setText("Parado");
        jLabelStatosDHCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosDHCPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosDHCPMouseEntered(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Firewall");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Postgres");

        jLabelStatosFirewall.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosFirewall.setForeground(java.awt.Color.red);
        jLabelStatosFirewall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosFirewall.setText("Parado");
        jLabelStatosFirewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosFirewallMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosFirewallMouseEntered(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Spooler");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Windows Update");

        jLabelStatosSpooler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosSpooler.setForeground(java.awt.Color.red);
        jLabelStatosSpooler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosSpooler.setText("Parado");
        jLabelStatosSpooler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosSpoolerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosSpoolerMouseEntered(evt);
            }
        });

        jLabelStatosWindowsUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosWindowsUpdate.setForeground(java.awt.Color.red);
        jLabelStatosWindowsUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosWindowsUpdate.setText("Parado");
        jLabelStatosWindowsUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosWindowsUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosWindowsUpdateMouseEntered(evt);
            }
        });

        jLabelStatosPostgres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatosPostgres.setForeground(java.awt.Color.red);
        jLabelStatosPostgres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatosPostgres.setText("Parado");
        jLabelStatosPostgres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatosPostgresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatosPostgresMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatosDNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatosFirewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatosSpooler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatosDHCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabelStatosWindowsUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatosPostgres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatosDNS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStatosDHCP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatosFirewall)
                    .addComponent(jLabelStatosPostgres, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatosSpooler)
                    .addComponent(jLabelStatosWindowsUpdate))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hardware", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelPlacaMae.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlacaMae.setText("Placa Mãe");

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelo.setForeground(new java.awt.Color(51, 0, 255));
        jLabelModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModelo.setText("Modelo");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Processador");

        jLabelProcessador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProcessador.setForeground(java.awt.Color.blue);
        jLabelProcessador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProcessador.setText("Null");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("IP");

        jLabelIP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIP.setForeground(java.awt.Color.blue);
        jLabelIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIP.setText("0.0.0.0");

        jLabelPlacaMae1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlacaMae1.setText("Memória");

        jLabelMemoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMemoria.setForeground(new java.awt.Color(51, 0, 255));
        jLabelMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMemoria.setText("GB");

        jLabelTipoIP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoIP.setForeground(java.awt.Color.red);
        jLabelTipoIP.setText("DHCP");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPlacaMae, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelProcessador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlacaMae1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTipoIP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlacaMae)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jLabelProcessador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlacaMae1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMemoria)
                    .addComponent(jLabelIP)
                    .addComponent(jLabelTipoIP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    
    private void jButtonPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPingActionPerformed
        //jProgressBarPing.setStringPainted(true);
            // TODO add your handling code here:
            //Funcoes.progressoPing(jProgressBarPing, true);
            //jProgressBarPing.setIndeterminate(true);

        try {
            Funcoes.ping(jLabelRecebidos, jLabelEnviados, jLabelMedia);
            Funcoes.velocidadeInternet(jSpinnerTamanhoDownload, jLabelTempoDownload, jLabelMediaDownload);
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPingActionPerformed
        
    private void jCheckBoxAthosBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAthosBackupActionPerformed
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("athosbackup");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxAthosBackupActionPerformed

    private void jCheckBoxDesempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDesempenhoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(!jCheckBoxDesempenho.isSelected())
                //Funcoes.opcoesDesempenho();
            Funcoes.setChecklist("desempenho");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxDesempenhoActionPerformed

    private void jCheckBoxWindowsUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWindowsUpdateActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("windowsupdate");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxWindowsUpdateActionPerformed

    private void jCheckBoxRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRedeActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("perfilderede");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxRedeActionPerformed

    private void jCheckBoxSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSiteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("site");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxSiteActionPerformed

    private void jCheckBoxWallpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWallpaperActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("wallpaper");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxWallpaperActionPerformed

    private void jCheckBoxInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInternetActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("opcoesdainternet");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxInternetActionPerformed

    private void jCheckBoxCapicomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCapicomActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Funcoes.setChecklist("capicom");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxCapicomActionPerformed

    private void jButtonPostgresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostgresActionPerformed
        try {
            // TODO add your handling code here:
            Funcoes.restartPostgres();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPostgresActionPerformed

    private void jButtonFirewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirewallActionPerformed
        try {
            // TODO add your handling code here:
            Funcoes.restartFirewall();
        } catch (IOException ex) {
            Funcoes.alerta("Firewall", "Erro ao reiniciar o Firewall!");
        }
        Funcoes.alerta("Firewall", "Firewall Reiniciado com sucesso!");
        try {
            Funcoes.liberaPorta();
        } catch (IOException ex) {
            Funcoes.alerta("Firewall", "Erro ao Liberar Portas!");
        }
        Funcoes.alerta("Firewall", "Porta 5432, foi Liberada na Entrada/Saída e nos protocolos TCP/UDP do Firewall");
    }//GEN-LAST:event_jButtonFirewallActionPerformed

    private void jButtonTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocarUsuarioActionPerformed
        try {
            
            Funcoes.trocarUsuario();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTrocarUsuarioActionPerformed

    private void jButtonEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnergiaActionPerformed
        try {
            // TODO add your handling code here:
            //Funcoes.alterEnergia(Funcoes.consultaEnergia());
            Funcoes.importEnergia();
            Funcoes.alerta("Plano de Energia", "Importado Plano de Energia");
            Funcoes.setEnergia(Funcoes.consultaEnergia());
            Funcoes.alerta("Plano de Energia", "Alterado Plano de Energia para 'Alto Desempenho'");
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEnergiaActionPerformed

    private void jButtonWinUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWinUpdateActionPerformed
        try {
            // TODO add your handling code here:
            Process comando = Runtime.getRuntime().exec("net stop wuauserv");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net stop bits");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net stop cryptsvc");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net stop msiserver");
            while(comando.isAlive()){
            }
            Funcoes.alerta("Windows Update", "Os Seguintes Serviços Foram PARADOS:\nWindows Update\nTransferência Inteligente de Plano de Fundo\nCriptografia\nWindows Installer");
            File SoftwareDistribution = new File("C:\\Windows\\SoftwareDistribution");
            File catroot2 = new File("C:\\Windows\\System32\\catroot2");
            if(!SoftwareDistribution.exists()){
                Funcoes.alerta("Windows Update", "A Pasta C:\\Windows\\SoftwareDistribution esta ocupada!");
            }else{
                File novoSoftwareDistribution = new File("C:\\Windows\\SoftwareDistribution.old");
                SoftwareDistribution.renameTo(novoSoftwareDistribution);
            }
            if(!catroot2.exists()){
                Funcoes.alerta("Windows Update", "A Pasta C:\\Windows\\System32\\catroot2 esta ocupada!");
            }else{
                File novocatroot2 = new File("C:\\Windows\\System32\\catroot2.old");
                catroot2.renameTo(novocatroot2);
            }
            comando = Runtime.getRuntime().exec("net start wuauserv");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net start bits");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net start cryptsvc");
            while(comando.isAlive()){
            }
            comando = Runtime.getRuntime().exec("net start msiserver");
            while(comando.isAlive()){
            }
            Funcoes.alerta("Windows Update", "Os Seguintes Serviços Foram INICIADOS:\nWindows Update\nTransferência Inteligente de Plano de Fundo\nCriptografia\nWindows Installer");
            
            
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonWinUpdateActionPerformed

    private void jLabelStatosDHCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosDHCPMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosDHCP.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start Dhcp");
                while(comando.isAlive()){     
                }
                jLabelStatosDHCP.setText("Iniciado");
                jLabelStatosDHCP.setForeground(Color.decode("#27992A"));
                comando = Runtime.getRuntime().exec("sc config Dhcp start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço DHCP", "Servido DHCP foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop Dhcp");
                while(comando.isAlive()){     
                }
                jLabelStatosDHCP.setText("Parado");
                jLabelStatosDHCP.setForeground(Color.red);
                comando = Runtime.getRuntime().exec("sc config Dhcp start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço DHCP", "Servido DHCP foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosDHCPMouseClicked

    private void jLabelStatosDHCPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosDHCPMouseEntered
        // TODO add your handling code here:
        jLabelStatosDHCP.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosDHCPMouseEntered

    private void jLabelStatosDNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosDNSMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosDNS.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start Dnscache");
                while(comando.isAlive()){     
                }
                jLabelStatosDNS.setText("Iniciado");
                jLabelStatosDNS.setForeground(Color.decode("#27992A"));
                comando = Runtime.getRuntime().exec("sc config wuauserv start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço DNS", "Servido DNS foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop Dnscache");
                while(comando.isAlive()){     
                }
                jLabelStatosDNS.setText("Parado");
                jLabelStatosDNS.setForeground(Color.red);
                comando = Runtime.getRuntime().exec("sc config wuauserv start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço DNS", "Servido DNS foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosDNSMouseClicked

    private void jLabelStatosDNSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosDNSMouseEntered
        // TODO add your handling code here:
        jLabelStatosDNS.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosDNSMouseEntered

    private void jLabelStatosFirewallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosFirewallMouseEntered
        // TODO add your handling code here:
        jLabelStatosFirewall.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosFirewallMouseEntered

    private void jLabelStatosPostgresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosPostgresMouseEntered
        // TODO add your handling code here:
        jLabelStatosPostgres.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosPostgresMouseEntered

    private void jLabelStatosWindowsUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosWindowsUpdateMouseEntered
        // TODO add your handling code here:
        jLabelStatosWindowsUpdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosWindowsUpdateMouseEntered

    private void jLabelStatosSpoolerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosSpoolerMouseEntered
        // TODO add your handling code here:
        jLabelStatosSpooler.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelStatosSpoolerMouseEntered

    private void jLabelStatosFirewallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosFirewallMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosFirewall.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start MpsSvc");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config MpsSvc start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço Firewall", "Servido Firewall foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop MpsSvc");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config MpsSvc start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço Firewall", "Servido Firewall foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosFirewallMouseClicked

    private void jLabelStatosPostgresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosPostgresMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosPostgres.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start postgresql-9.0");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config postgresql-9.0 start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço Postgres", "Servido Postgres foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop postgresql-9.0");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config postgresql-9.0 start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço Postgres", "Servido Postgres foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosPostgresMouseClicked

    private void jLabelStatosSpoolerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosSpoolerMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosSpooler.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start Spooler");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config Spooler start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço Spooler", "Servido Spooler foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop Spooler");
                while(comando.isAlive()){     
                }
                
                comando = Runtime.getRuntime().exec("sc config Spooler start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço Spooler", "Servido Spooler foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosSpoolerMouseClicked

    private void jLabelStatosWindowsUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatosWindowsUpdateMouseClicked
        // TODO add your handling code here:
        if(jLabelStatosWindowsUpdate.getText().equals("Parado")){
            try {
                Process comando = Runtime.getRuntime().exec("net start wuauserv");
                while(comando.isAlive()){     
                }
                comando = Runtime.getRuntime().exec("sc config wuauserv start= auto");
                while(comando.isAlive()){     
                }   
                Funcoes.alerta("Serviço Windows Update", "Servido Windows Update foi Ativado");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            try {
                Process comando = Runtime.getRuntime().exec("net stop wuauserv");
                while(comando.isAlive()){     
                }
                comando = Runtime.getRuntime().exec("sc config wuauserv start= disabled");
                while(comando.isAlive()){     
                }
                Funcoes.alerta("Serviço Windows Update", "Servido Windows Update foi Desativado");
                   
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelStatosWindowsUpdateMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnergia;
    private javax.swing.JButton jButtonFirewall;
    private javax.swing.JButton jButtonPing;
    private javax.swing.JButton jButtonPostgres;
    private javax.swing.JButton jButtonRelogio;
    private javax.swing.JButton jButtonTrocarUsuario;
    private javax.swing.JButton jButtonWinUpdate;
    private javax.swing.JCheckBox jCheckBoxAthosBackup;
    private javax.swing.JCheckBox jCheckBoxCapicom;
    private javax.swing.JCheckBox jCheckBoxDesempenho;
    private javax.swing.JCheckBox jCheckBoxInternet;
    private javax.swing.JCheckBox jCheckBoxRede;
    private javax.swing.JCheckBox jCheckBoxSite;
    private javax.swing.JCheckBox jCheckBoxWallpaper;
    private javax.swing.JCheckBox jCheckBoxWindowsUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelAdobeReader;
    private javax.swing.JLabel jLabelAdobeReadertxt;
    private javax.swing.JLabel jLabelAthosInstalado;
    private javax.swing.JLabel jLabelAthosPostgres;
    private javax.swing.JLabel jLabelAtiveAdmin;
    private javax.swing.JLabel jLabelAvast;
    private javax.swing.JLabel jLabelAvasttxt;
    private javax.swing.JLabel jLabelDropbox;
    private javax.swing.JLabel jLabelDropboxtxt;
    private javax.swing.JLabel jLabelEnergia;
    private javax.swing.JLabel jLabelEnviados;
    private javax.swing.JLabel jLabelEnviadostxt;
    private javax.swing.JLabel jLabelFirewall;
    private javax.swing.JLabel jLabelGoogleChrome;
    private javax.swing.JLabel jLabelGoogleChrometxt;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelKlite;
    private javax.swing.JLabel jLabelKlitetxt1;
    private javax.swing.JLabel jLabelLightGreenOff;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JLabel jLabelMediaDownload;
    private javax.swing.JLabel jLabelMemoria;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMédia;
    private javax.swing.JLabel jLabelOffice;
    private javax.swing.JLabel jLabelOfficetxt;
    private javax.swing.JLabel jLabelOutput;
    private javax.swing.JLabel jLabelPlacaMae;
    private javax.swing.JLabel jLabelPlacaMae1;
    private javax.swing.JLabel jLabelProcessador;
    private javax.swing.JLabel jLabelRecebidos;
    private javax.swing.JLabel jLabelRecebidostxt;
    private javax.swing.JLabel jLabelRestartPostgres;
    private javax.swing.JLabel jLabelStatosDHCP;
    private javax.swing.JLabel jLabelStatosDNS;
    private javax.swing.JLabel jLabelStatosFirewall;
    private javax.swing.JLabel jLabelStatosPostgres;
    private javax.swing.JLabel jLabelStatosSpooler;
    private javax.swing.JLabel jLabelStatosWindowsUpdate;
    private javax.swing.JLabel jLabelTempoDownload;
    private javax.swing.JLabel jLabelTipoIP;
    private javax.swing.JLabel jLabelTrocarUsuario;
    private javax.swing.JLabel jLabelVersaoWindows;
    private javax.swing.JLabel jLabelVersaoWindowsText;
    private javax.swing.JLabel jLabelWinrar;
    private javax.swing.JLabel jLabelWinrartxt;
    private javax.swing.JLabel jLabeldotNet;
    private javax.swing.JLabel jLabeldotNettxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBarPing;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerTamanhoDownload;
    // End of variables declaration//GEN-END:variables

    
    
    
}
